# Default values for simplifieds3bucket-deployment-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

simplifiedS3Bucket:
  image: rajumakadenice/simplifieds3bucket
  name: simplifieds3bucketservice

volumeMounts:
  name: simplifieds3bucket-storage
  mountPath: /data/simplifieds3bucket  
  
ports:
  containerPort: 5050
  clusterIpPort: 80
  nodeTargetPort: 5050
  nodePort: 30005